jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - name: Install Hugo
        run: |
          wget -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.152.2/hugo_extended_0.152.2_linux-amd64.deb
          sudo dpkg -i hugo.deb
      - name: Build site
        run: hugo --gc --minify
      - name: Deploy
        uses: actions/deploy-pages@v2
        with:
          source_dir: ./public
